### ISSUE TITLE
Maven and Junit

### ISSUE THREAD

**Issue by Alejandro-Rojas** [MSU-CS3250-DreamTeam/Database#16]
Push all the java files as a Maven package, the organization/package name will be com.dreamteam.database. We will have to import com.dreamteam.database; to every class to make it one package. This will allow me to implement Maven and Junit easier.

**Comment by JonathanGrant92** [comment]
Ok, I didn't notice this yesterday, when I was messing with the project structure. I'll look into it today though.

**Comment by Alejandro-Rojas** [comment]
Great looks like it is one package now with maven. closing this issue
