### ISSUE TITLE
Things that are left to do

### ISSUE THREAD

**Issue by Alejandro-Rojas** [MSU-CS3250-DreamTeam/Database#29]
- work on the Create option where it adds info, that the user created through the user menu into the console.  
- work on the update option where once the user inputs the info into the console it saves and updates to csv file. When 3 update is selected from user menu. 
- work on the delete option where user can delete info 
- We will just use (command  + F) on the keyboard to search the list for a specific item to modify or delete. 
- get the Read option to  parse the file. 
- I am having hard time creating the junit testing so idk if we will have one.

**Comment by JonathanGrant92** [comment]
"We will just use (command + F) on the keyboard to search the list for a specific item to modify or delete."

Sorry, I only noticed these now. This one looks interesting.

**Comment by Alejandro-Rojas** [comment]
will close this for now.
