### ISSUE TITLE
database delete method

### ISSUE THREAD

**Issue by JonathanGrant92** [MSU-CS3250-DreamTeam/Database#7]
Draft the delete method algorithm/code.

**Comment by alexandersanford** [comment]
Working on this one. Definitely want to test, but I wanted to get something in there that should work. Let me know if there's a more efficient way to get to the database entry in order to delete it.

**Comment by JonathanGrant92** [comment]
Pass an identifier like a product id to a search method and presume it will give back the correct result when it's implemented.

**Comment by Alejandro-Rojas** [comment]
Please see a way once you finish to implement this into our main class which has a user menu. Thanks. Let us know if you need help or just wants us to check it. Please push what you have so far so we can see what needs to be fix or added.
